### ISSUE TITLE
Graph asset inspector

### ISSUE THREAD

**Issue by rutkoski** [simeonradivoev/UIElementNodeGraph#1]
First of all, great work.

I don't know if this is a bug, if it's intended, or not implemented yet, but shouldn't the graph properties appear on the inspector when the graph's scriptable object is selected?

**Comment by simeonradivoev** [comment]
You need a custom inspector for that. I don't see a need to add one as the GraphObjects differ for each use-case. Also, all needed UI for the graph should be in the graph editor window.
